version: '3.6'

services:
  mysql:
    image: mysql:5.6
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    container_name: "mysql"
    hostname: mysql
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
    tty: true
  api:
    build: .
    hostname: api
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/anielski/download-url-in-go
    restart: on-failure